### PR TITLE
Move sortedrun under package

### PR DESCRIPTION
**Pull request by naveen246**
Move sortedrun to compacted package
Move tablestore to store package

### CODE REVIEW

**Comment by thrawn01** [comment]
I think we should move these packages under `internal/` and eventually remove the `slatedb/` directory.

**Comment by thrawn01** [comment]
What about calling it `compaction` instead of `compacted` ? I say this because I that is what the package does, as apposed to what the package's final outcome is. It's subtle, but should avoid confusion.

**Comment by naveen246** [comment]
> I think we should move these packages under `internal/` and eventually remove the `slatedb/` directory.

will do this in future PRs

**Comment by naveen246** [comment]
> What about calling it `compaction` instead of `compacted` ? I say this because I that is what the package does, as apposed to what the package's final outcome is. It's subtle, but should avoid confusion.

Changed to `compaction`

**Review by thrawn01 — APPROVED** [review]

**Pull request merged**
